spring.application.name=homework2_mybatis

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/homework2_mybatis_db
spring.datasource.username=postgres
spring.datasource.password=240904
